### ISSUE TITLE
fails to install on laravel homestead

### ISSUE THREAD

**Issue by TheSachin** [antaresproject/project#101]

**Comment by mountstone** [comment]
Hello @TheSachin 

Cannot confirm laravel homestead installation problems.

Please check your vagrant  environment meets requirements described here:
http://www.docs.antaresproject.io/php-framework/0.9.2/installation/requirements/index.html

Next time, read Issues Reporting Guide (http://www.docs.antaresproject.io/php-framework/0.9.2/getting_started/issues_reporting_guide/index.html
) to give more details.
