### ISSUE TITLE
Platform has not been installed -error on installation

### ISSUE THREAD

**Issue by sandysh** [antaresproject/project#104]
I am facing issue with antares installation. On fourth step on web installer i get error "Platform has not been installed". I would like to know what kind of error is this and how can i be able to resolve it. 

Thank you.

**Comment by mountstone** [comment]
@sandysh 

First of all, Thank you for interesting Antares.

Could you please provide more details, by sharing log files located at:
```
storage/logs/
````

It will help us to resolve problem you requested.
