### ISSUE TITLE
Recent activity widget looks bad with the empty data

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/project#12]
- There shouldn’t be grey linRecent activity widget looks bad with the empty data
- e below filter/search
- Actually, there shouldn’t be filter/search available
- The empty data message should be centered properly.

http://puu.sh/uwp49/051a1e6c91.png

**Comment by mountstone** [comment]
@konradkeck @dawid-g done

**Comment by dawid-g** [comment]
Verified as fixed.
