### ISSUE TITLE
SUGGESTION: Alert messages should have OK/Confirm (positive action)

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/project#16]
SUGGESTION: Alert messages should have OK/Confirm (positive action) on the LEFT side. I may be wrong, but I think it’s more intuitive.

http://puu.sh/uwpp8/c5e2bf808c.png

**Comment by mountstone** [comment]
@konradkeck done
@dawid-g  please review

**Comment by dawid-g** [comment]
Verified as fixed.

**Comment by mountstone** [comment]
@tehaiks it your commit has overwrited change

**Comment by tehaiks** [comment]
@mountstone reverting in next update.
