### ISSUE TITLE
Mail Configuration UI improvements

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/project#22]
1. Fields should have tips: 
- Typical values (if possible) - especially for port and sendmail command
- Example values (if possible)

2. SMTP -> Encryption - cannot this field be a dropdown?

3. Test connection button:
- Should be in the middle between submit and cancel
- Should be white in the middle with coloured border and text
- Should have branded colors

http://puu.sh/uwpRR/5cb6f0eb0f.png

**Comment by mountstone** [comment]
@konradkeck done
@dawid-g please review

**Comment by dawid-g** [comment]
Verified as fixed.
