### ISSUE TITLE
Automation page marks Logs link as active 

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/project#29]
http://puu.sh/uwqf3/3c09d401a0.png

(same for Notification Templates)

**Comment by mountstone** [comment]
@konradkeck @dawid-g done

**Comment by dawid-g** [comment]
Automation page displayed error: https://puu.sh/uRtgz/eeeeb4a6b6.png

**Comment by mountstone** [comment]
@dawid-g recheck

**Comment by dawid-g** [comment]
Verified as fixed.
