### ISSUE TITLE
Branding 

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/project#30]
- In the main menu, it should be named “Branding”, not “Brand Settings”
- Same for the breadcrumbs (right now it’s “Brand Edit Antares”)
- Subpages (like email branding) should have Branding > Section Name breadcrumbs.
- Composition field (in area settings) is not having branding colors.
- When on the area settings, the pointer in the menu is a square
http://puu.sh/uwqmr/aa66efcafc.jpg

**Comment by mountstone** [comment]
@konradkeck @dawid-g done

**Comment by dawid-g** [comment]
Verified as fixed.
