### ISSUE TITLE
Creating New Custom Field

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/project#33]
1. Creating new Fieldset for a custom field is not possible - providing a text to the field doesn’t take the effect
2. Field type should be in the “Field Options” section

3. Naming:
- Select field validators -> Validation
-What are the “value” coming for and why are there default values?
http://puu.sh/uwqBf/350130b1cc.png

If the “value” goes for the previous field (like the second “Value” goes for “Maximum” property), it should be:  

- Invisible if the checkbox is not selected
- Have bettter label!! Or, it may just not have a label but appear next to the checkbox?

4. Submit and cancel buttons should be just like on the other sections:
http://puu.sh/uwqNv/4159aabea8.png

**Comment by mountstone** [comment]
@konradkeck @dawid-g done

**Comment by dawid-g** [comment]
Verified as fixed.
