### ISSUE TITLE
Logs naming

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/project#36]
- Api Logs -> API Log
- Automation Logs -> Automation Log
- Notification Logs -> Notification Log

**Comment by mountstone** [comment]
@konradkeck @dawid-g done

**Comment by dawid-g** [comment]
Now is "Api Log". Should be "API Log"

**Comment by mountstone** [comment]
@dawid-g recheck

**Comment by dawid-g** [comment]
Fixed,
