### ISSUE TITLE
Creating new backup improvements

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/project#39]
- Creating new backup should add a backup to the list, with status “Pending” if there is a task created for the automation. 
- It should be also possible to remove a pending task which will remove the task from the queue.
- If the backup is already in progress, it should be visible as “in progress” status without an option to remove/delete it.
- Once the backup is complete, the status should be “completed”

**Comment by mountstone** [comment]
@konradkeck @dawid-g done

**Comment by dawid-g** [comment]
There is no possibility to remove a pending task actually: "Backup-job has not been deleted from queque"

**Comment by mountstone** [comment]
@dawid-g recheck

**Comment by dawid-g** [comment]
Verified as fixed.
