### ISSUE TITLE
Creating sandbox throws Twig Error Runtime

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/project#40]
An exception has been thrown during the rendering of a template ("file_put_contents(/var/www/html/builds/build_0_9_0/public/packages/administrators_updater_update.js): failed to open stream: No such file or directory") in "antares/foundation::layouts.antares.partials._scripts_webpack" at line 6.
/var/www/html/builds/build_0_9_0/vendor/twig/twig/lib/Twig/Template.php "447"
435                 $e->setSourceContext($this->getSourceContext());
436             }
437 
438             // this is mostly useful for Twig_Error_Loader exceptions
439             // see Twig_Error_Loader
440             if (false === $e->getTemplateLine()) {
441                 $e->setTemplateLine(-1);
442                 $e->guess();
443             }
444 
445             throw $e;
446         } catch (Exception $e) {
447             throw new Twig_Error_Runtime(sprintf('An exception has been thrown during the rendering of a template ("%s").', $e->getMessage()), -1, $this->getSourceContext(), $e);
448         }
449     }
450 
451     /**
452      * Auto-generated method to display the template with the given context.
453      *
454      * @param array $context An array of parameters to pass to the template
455      * @param array $blocks  An array of blocks to pass to the template
456      */
457     abstract protected function doDisplay(array $context, array $blocks = array());
458 
459     /**

**Comment by mountstone** [comment]
@konradkeck @dawid-g done

**Comment by dawid-g** [comment]
Verified as fixed.
