### ISSUE TITLE
Hardly visible scroll

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/project#42]
If there are larger sections/form scroll is hardly visible on the right, and it seems to be cut. Maybe there should be some gradient or shadow?

https://puu.sh/uMUPM/b027d3c95d.png

There should be shadow if there are more elements.

**Comment by tehaiks** [comment]
@dawid-g A lot of scroll fixes have been made, but I'm not sure what do you mean exactly on this issue. Are you talking about vertical or horizontal scroll?
