### ISSUE TITLE
[Proposal] Create .env.example file

### ISSUE THREAD

**Issue by Germanaz0** [antaresproject/project#5]
It is missing an .env.example file with all the needed configurations that it needs, like DB, Redis config, etc...

**Comment by mountstone** [comment]
@Germanaz0 The project settings are not yet fully completed. We know abt most of issues you are reporting. Please be patient.

**Comment by Germanaz0** [comment]
@mountstone sorry, just wanted to list what I have found so far

**Comment by mountstone** [comment]
@Germanaz0 thank you for feedbacks :)

**Comment by mountstone** [comment]
@Germanaz0 env.example has been added to repo.
