### ISSUE TITLE
Install not working

### ISSUE THREAD

**Issue by Teumel** [antaresproject/project#55]
Hello everyone,
If I'am trying to execute - `composer create-project antaresproject/project /var/www/html dev-master --keep-vcs` (taken from the docs)
The following problems are displayed:

```
 Problem 1
    - The requested package antaresproject/component-installer-plugin 0.9.2.1-dev exists as antaresproject/component-installer-plugin[0.9.2.x-dev, dev-master] but these are rejected by your constraint.
  Problem 2
    - antaresproject/module-api dev-master requires antaresproject/component-installer-plugin 0.9.2.1-dev -> no matching package found.
    - antaresproject/module-api dev-master requires antaresproject/component-installer-plugin 0.9.2.1-dev -> no matching package found.
    - Installation request for antaresproject/module-api dev-master -> satisfiable by antaresproject/module-api[dev-master].
```

Is there maybe an issue at the moment with nameings within the component-installer-plugin (composer.json)? 
I tried diffrent workarround, but i didn't get a fresh installation to work.
Thanks for looking into this.

Joerg

**Comment by mountstone** [comment]
Hi @Teumel 
Thx for the issue.  The error was related to the missing version of composer plugin. 
We are currently working with some cleans within repos. Installation should already work.

**Comment by Teumel** [comment]
@mountstone 
You made my day! Thanks you very much for fixing this within minutes. Awesome I can confirm that the installation now is working as expected. Now I'am looking forward to see the Antares-Project in action. Thanks again
Joerg

**Comment by mountstone** [comment]
Thank you @Teumel

**Comment by bajki** [comment]
Not working again!

**Comment by mountstone** [comment]
@bajki 
Thx for the issue. Composer configuration has been updated. You shouldn't have any installation problems anymore.

**Comment by bajki** [comment]
It gives error: antaresproject/component-installer-plugin 0.9.2.1-dev requires composer-plugin-api ^1.1 -> no matching package found.

**Comment by mountstone** [comment]
@bajki 

Are you sure you are installing correct verion which is described in [official documentation](http://www.docs.antaresproject.io/php-framework/installation/manual-installation-guide/#antares-installation) ?

You should use, as follows:
```
composer create-project antaresproject/project /var/www/html dev-master --keep-vcs
```

Please read [Issues Reporting Guide](http://www.docs.antaresproject.io/php-framework/getting-started/issues-reporting-guide/)  before report any issue.

**Comment by bajki** [comment]
![untitled](https://user-images.githubusercontent.com/24210611/29916351-ca73177c-8e3e-11e7-9a54-4061c0265969.png)

**Comment by MarcinKozak** [comment]
Hi @bajki

Try run `composer require composer/composer` as it contains necessary files for API.

**Comment by mountstone** [comment]
@bajki 

Could you provide more details about your server environment?

It is described in [official documentation](http://www.docs.antaresproject.io/php-framework/getting-started/issues-reporting-guide/): "The version of PHP and repository branch. The type of OS and Web server"

We need info about:

- Apache version
- PHP version
- Mysql version
- Composer version
- Git version

http://www.docs.antaresproject.io/php-framework/installation/requirements/#required-libraries

We will try to simulate your environment and situation.
