### ISSUE TITLE
Installing antares project in Laravel homestead with Nginx

### ISSUE THREAD

**Issue by giddyeffects** [antaresproject/project#56]
Hi,
The instructions for installing antares requires one to install Apache server. Therefore, how does one install the antares project in a virtual machine with Laravel homestead, with Nginx installed and I don't want to install Apache?
Also I was getting this error when I tried to install using <ip-address>/install

**Symfony\Component\Debug\Exception\FatalThrowableError

Call to undefined function Antares\Installation\apache_get_modules()

/home/vagrant/Code/antares/src/core/src/modules/installer/src/Requirement.php "239"**

Which is expected since Apache is not installed.

**Comment by mountstone** [comment]
Hello @giddyeffects 

We will add support for Nginx in next releases. 
Stay in touch with us :)

**Comment by TheSachin** [comment]
Hi any status update on this?

**Comment by konradkeck** [comment]
Yes, we're now finishing v0.9.2 that will include the Nginx support. We expect it done in October.

**Comment by giddyeffects** [comment]
Any update?

**Comment by mountstone** [comment]
@giddyeffects Nginx support has been added into branch 0.9.2. We are still working on some front end and backend issues, but official release of 0.9.2 has not been confirmed yet. Please be patient.

**Comment by konradkeck** [comment]
@giddyeffects as the 0.9.2 has been finished, nginx support has been added. Soon, we will write a blog article showing benefits of using it - it provides a great performance comparing to Apache.

**Comment by TheSkyHeart** [comment]
Hi Guys,

any update on the article for nginx, we only use nginx and we would like to try Antares with nginx.
