### ISSUE TITLE
[Branding] No possibility to delete incorrect logo file

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/project#60]
1. Go to admin/branding/area/1
2. Upload to large file

Results:

There is no possibility to delete this file without page refresh

![logo](https://user-images.githubusercontent.com/26220123/32898344-330ec2b4-cae8-11e7-9e9c-41bda7307c14.gif)

**Comment by mountstone** [comment]
fixed

**Comment by dawid-g** [comment]
Reopen, something like that:


![logo](https://user-images.githubusercontent.com/26220123/33068287-06dfb230-ceb1-11e7-932a-1ab9f60c7a82.gif)

**Comment by tehaiks** [comment]
@dawid-g Can you re-check the issue at hand?

**Comment by dawid-g** [comment]
It's ok now. Closed.
