### ISSUE TITLE
[Branding] Favicon disappears after a page refresh

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/project#61]
1. Go to admin/branding/area/1
2. Upload new, correct file to favicon 
3. Refresh the page

Results:

Favicon returns to the previous one

The same case is with 'Logo'.

![favicon](https://user-images.githubusercontent.com/26220123/32898724-36a1a5ee-cae9-11e7-82ad-f827642bb354.gif)

**Comment by mountstone** [comment]
fixed
