### ISSUE TITLE
[Branding] Contradictory information about logo size

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/project#63]
Go to: /admin/branding/area/1

When I upload too large logo file to Logo field, there is information that "max width is 192px": https://image.prntscr.com/image/hegH-CiXQUmeiyOM4g11FA.png

But "?" button under the field of the logo shows info about "Recommended min width: 512px":
https://image.prntscr.com/image/oc0WmGPkRh2xM8OYuoaCQg.png

If max with = 192 px recommeded can't be bigger (512px).

**Comment by mountstone** [comment]
fixed
