### ISSUE TITLE
[Brand] Brand Settings - The url format is invalid.

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/project#65]
1. Go to Brand Settings section (admin/branding)
2. Change some, random data
3. Click Submit

Results:

Despite the fact there is valid format in Brand URL field, there is displayed error message:

"The url format is invalid."

https://image.prntscr.com/image/SSD7kBDCTQyvoFUPXWEAUg.png

**Comment by mountstone** [comment]
@dawid-g 

There is no case to use format like this: http://ip:port. 

Remove :port and recheck it.

**Comment by dawid-g** [comment]
Yes, you're right. Closed.
