### ISSUE TITLE
Translations -> Add Language - INTERNAL SERVER ERROR

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/project#66]
1. Go to Translations -> Manage Languages
2. Click "Add" (/admin/translations/languages/add)

Results:

https://image.prntscr.com/image/h0yMNivlR7ioix6Tc_cmtA.png

**Comment by mountstone** [comment]
@dawid-g Fixed

**Comment by dawid-g** [comment]
confirmed.

**Comment by dawid-g** [comment]
The issue is back. I entered code:12, name: test

Results:
https://image.prntscr.com/image/a7pTEv6iTma4Eqx9Q5nVwA.png

**Comment by mountstone** [comment]
@dawid-g unable to reproduce the error

**Comment by dawid-g** [comment]
Ok, it's work now. Closed.
