### ISSUE TITLE
[Module] No possibility to deactivate the modules

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/project#68]
1. Go to: /admin/modules
2. Click "deactivate" for random module

Results:

![deactivation](https://user-images.githubusercontent.com/26220123/33019278-ea8e3f46-cdf9-11e7-9d24-62e20bcf7e01.gif)

The same case is with the installation or activate process.

**Comment by MarcinKozak** [comment]
@dawid-g fixed - warning about invalid files permissions will be shown

**Comment by dawid-g** [comment]
There are still "preview" displayed, modules are not deactivating.

https://image.prntscr.com/image/-n4Xh7rLT7CkLMuGLOkr9Q.png

**Comment by MarcinKozak** [comment]
@dawid-g Fixes included to Installation and Core modules.

**Comment by dawid-g** [comment]
I have something like that now:  https://image.prntscr.com/image/JBbWetwaQwGL_6bUUaiLrQ.png

**Comment by dawid-g** [comment]
Edit. I have installed Antares app by manual installation, and that issue not occure. 

There is problem with two factor although the module is activated, it is not available anywhere in the application.
