### ISSUE TITLE
Notifications/Alerts - "No items found" - despite the a lot of action was making

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/project#69]
https://image.prntscr.com/image/9Qek27YXTyWWry2C2nJN1g.png
https://image.prntscr.com/image/zvEeI0MfSUW31ShQo_KYoQ.png

There is "No items found" all the time displayed for Notifications/Alerts, despite the a lot of action was making

**Comment by MarcinKozak** [comment]
@dawid-g fixed

**Comment by dawid-g** [comment]
@mountstone @MarcinKozak  which actions should be displayed in these tabs precisely?

Things like adding and removing users or status changing should be ? currently not being displayed.

**Comment by MarcinKozak** [comment]
@dawid-g  It depend of for each notification configuration. The type field (notification, alert) is for sidebar notifications.

**Comment by dawid-g** [comment]
Ok, closed.
