### ISSUE TITLE
Missing davejamesmiller/breadcrumbs in Composer

### ISSUE THREAD

**Issue by Szkalownik** [antaresproject/project#7]
Error recived when I runned comoser: 
![breadcrumbs-missing-composer](https://cloud.githubusercontent.com/assets/25772035/22933568/412c437a-f2cc-11e6-9911-971dc9f6e98e.png)

So its looks like this library is missing in composer.json requires.

**Comment by Germanaz0** [comment]
You should run with `composer install --dev` or if this does not work, just hardcode your `composer.json` file (just a temporary solution) and add inside require:

   "davejamesmiller/laravel-breadcrumbs": "dev-master"

**Comment by mountstone** [comment]
Mentioned vendors has been deleted from core dependencies. It has been added to project composer as require-dev. In next release, davejamesmiller/laravel-breadcrumbs will be all removed.
