### ISSUE TITLE
Langs

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/project#70]
- [x]  1 . admin/sample_module/configuration - after "Submit" clicking: https://image.prntscr.com/image/m0QYdDeQTjSmgReY8HKNww.png

- [x]  2. admin/branding https://image.prntscr.com/image/ylwXgtVCQqC99-sRaqpc8g.png

- [x] 3. admin/users/index -> With Selected  https://image.prntscr.com/image/jLw9Ig7rRTGV6uCfTBkfYQ.png

**Comment by mountstone** [comment]
@dawid-g fixed

**Comment by dawid-g** [comment]
confirmed.

**Comment by dawid-g** [comment]
Reopen: admin/users/index - https://image.prntscr.com/image/t6iEUAxZS7GLxI-JI37jtA.png

**Comment by mountstone** [comment]
@dawid-g fixed

**Comment by dawid-g** [comment]
verified as fixed.
