### ISSUE TITLE
Custom field deleting case

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/project#72]
/admin/customfields/user/index

If I have added a new custom field, there was possibility to delete it with no errors, but when I try to delete one of these https://image.prntscr.com/image/Ojm318YKSYG4rag5Jz4zNw.png  - is displaying success validation, but custom field still exist.

**Comment by mountstone** [comment]
@dawid-g 

Some custom fields has been defined as hard-coded, and cannot be deleted.  
Gender and url are sample fields defined by developer.

**Comment by dawid-g** [comment]
Ok, copy that.
