### ISSUE TITLE
Activity Log - "Delete" doesn't respond

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/project#73]
1. Go to: /admin/logger/activity/index#
2. Click Activity Log -> Delete

Results:
"Delete" doesn't respond

![del](https://user-images.githubusercontent.com/26220123/33071155-b288e0bc-ceba-11e7-911d-47063c46402a.gif)

**Comment by mountstone** [comment]
@dawid-g fixed

**Comment by dawid-g** [comment]
Confirmed.
