### ISSUE TITLE
Account Details section - two cases

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/project#75]
1. Go to: /admin/account
2. Change Default language and Gender
3. Click Submit

Results:
1. Language field is back to English, gender field is back to "M"
2. In password field is entered some string https://image.prntscr.com/image/IXld_pE2T_KgdMCLqHfI8A.png

Issue occure on every browsers.

**Comment by mountstone** [comment]
@dawid-g fixed

**Comment by dawid-g** [comment]
confirm, repaired.
