### ISSUE TITLE
Forgot Password - Target  is not instantiable.

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/project#77]
1. Go to "Forgot Password"
2. Enter correct email
3. Click Reset Password

Results:
https://image.prntscr.com/image/20s5dZtJRn_tkhFUJPnl5w.png

**Comment by mountstone** [comment]
@dawid-g fixed

**Comment by dawid-g** [comment]
I have correct email configuration, my own admin account and despite validations about correct sending, I do not receive an e-mail with resetting my password.

**Comment by dawid-g** [comment]
It's ok now, closed.
