### ISSUE TITLE
User profile - "Send Notification" widget

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/project#78]
/admin/users/35 - there is "SEND NOTIFICATION" widget which does not perform any action. 

Actual results during clicking on Send or Test:
https://image.prntscr.com/image/-K6In3vvTGSH5oumh9CDfA.png

**Comment by MarcinKozak** [comment]
@dawid-g 
Without any details of request and response I can reproduce the issue. In my own tests I only get 500 for notifications which are not finished. If you have that problem with the "New Device Detected" notification make sure if you have the last version of Logger module.

**Comment by mountstone** [comment]
@MarcinKozak User should have default email notifications such as new device detection and should be sendable from widget - on demand. 

When notification channel does not have any notifications, just add placeholder to with zero data message.

**Comment by MarcinKozak** [comment]
@dawid-g 

Zero data for widget added.
Restricted  selectable notification for device detection.

**Comment by dawid-g** [comment]
"Zero data" - confirmed.
I have added new device template, it is displayed in user profil, but when I try send Test, or Send a Mail Notification, there are still 404 error: 

https://image.prntscr.com/image/AYdF1iRLQMC_AftJ-Yd21A.png

/admin/users/26

**Comment by MarcinKozak** [comment]
@dawid-g 404 errors fixed in Core module.

**Comment by dawid-g** [comment]
I have still 404 error with something lika that in response:

https://image.prntscr.com/image/Mn4Pw0mbRqmA2RzZ_Ci7hw.png
