### ISSUE TITLE
[AA] After switching to username profile, the console shows errors

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/project#79]
Preconditions: 
- Full Top menu

Go to: admin/users/35#

Results:
After switching to username profile, the console shows errors

https://image.prntscr.com/image/rnYTMG4ITLCBo3QQ13TtgA.png

**Comment by tehaiks** [comment]
@dawid-g Please recheck the test case.

**Comment by dawid-g** [comment]
It's ok now, closed.
