### ISSUE TITLE
Custom Fields - Filter does not carry out any action

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/project#82]
Precondition:
-Full Top Menu View

1. Go to: /admin/customfields/user/index
2. There are created some fields (group user), choose filter by group: select

Results:
No action was performed

**Comment by dawid-g** [comment]
Similar situation with /admin/acl/index/users

**Comment by dawid-g** [comment]
And with filter by status on Users list (admin/users/index)

**Comment by mountstone** [comment]
@dawid-g fixed

**Comment by dawid-g** [comment]
verified as fixed.
