### ISSUE TITLE
User list - "trying to get property of non-object" string displayed

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/project#89]
1. Delete user from user list
2. Open random user profile by double mouse click

Results:

![trying](https://user-images.githubusercontent.com/26220123/33122653-189c8e4a-cf78-11e7-88c7-a2e55d747696.gif)

**Comment by mountstone** [comment]
@dawid-g unable to reproduce the error

**Comment by dawid-g** [comment]
ok, its ok now.
