### ISSUE TITLE
User edit - some string in password field

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/project#95]
Go to: http://10.10.10.35:73/admin/users/26/edit

Results:
There is some string in password field

Case occure on all browsers.

**Comment by mountstone** [comment]
@dawid-g fixed

**Comment by dawid-g** [comment]
the same case here:

http://10.10.10.35:73/admin/acl/index/users/25/edit

**Comment by mountstone** [comment]
@dawid-g will be fixed in next release
