### ISSUE TITLE
User adding - 500 internal server error

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/project#96]
1. Go to admin/users/create
2. Enter valid data, and click Submit

Results:
https://image.prntscr.com/image/7LerDofyRbqzoq8WqEpMdA.png

**Comment by mountstone** [comment]
@MarcinKozak 

```
Method routeNotificationFor does not exist.
```

**Comment by MarcinKozak** [comment]
@mountstone @dawid-g fixed

**Comment by dawid-g** [comment]
verified as fixed.
