### ISSUE TITLE
302 - Too Many Requests

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/project#99]
1. Go to Dashboard
2. Refresh the page several time (not too fast) 

Results:
https://image.prntscr.com/image/NjKxTqUDRHiE_QjFSOv0fw.png

![requests](https://user-images.githubusercontent.com/26220123/33615145-9a1b8d7a-d9d9-11e7-9abf-e189903aae6b.gif)

**Comment by mountstone** [comment]
@dawid-g Fixed

**Comment by dawid-g** [comment]
verified to be fixed.
